server:
  port: 8810
spring:
  profiles:
    active: dev
  application:
    name: wiki

---
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  profiles: dev
  rabbitmq:
    host: 192.168.100.249
    port: 5672