server:
  port: 8810
spring:
  profiles:
    active: dev
  application:
    name: wiki

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  profiles: dev
  rabbitmq:
    host: 192.168.100.249
    port: 5672