server:
  port: 8610
spring:
  profiles:
    active: dev
  application:
    name: demo

---
spring:
  profiles: dev
  rabbitmq:
    host: 192.168.100.249
    port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/